### ISSUE TITLE
Pinch gesture not working

### ISSUE THREAD

**Issue by sidevesh** [sidevesh/gnome-gesture-improvements--transpiled#1]
Originally reported at https://github.com/harshadgavali/gnome-gesture-improvements/issues/206#issuecomment-2028459608

**Comment by zei-bit** [comment]
I just wanted to express my interest in this bug fix. Unfortunately, I'm not very knowledgeable in this area, but I'd be happy to test it! Thanks for all you've done so far!

**Comment by FlynnD273** [comment]
Alright so I've done some digging and logging, and it seems that the extension is connecting to a signal from `global.stage` called `captured-event::touchpad`, [in the code here](https://github.com/sidevesh/gnome-gesture-improvements--transpiled/blob/3bc46f0c3804c3a399b3023598445b819e665af0/gestureImprovements%40gestures/src/trackers/pinchTracker.js#L90). It's not even activating on a pinch gesture. However, it seems I'm able to perform the pinch gestures when the cursor is over a GNOME UI element, like the top bar. I have no idea why. This... seems like a GNOME issue and not an extension issue though. Everything else seems to be functioning properly.

**Comment by FlynnD273** [comment]
Oh wait a second, the swipe and pinch trackers are two different things. So maybe if we could figure out the difference between the two?

**Comment by FlynnD273** [comment]
I have submitted an issue [here](https://gitlab.gnome.org/GNOME/mutter/-/issues/3505) in the Mutter project, I did a little digging and I'm fairly certain this isn't an issue with this extension.

**Comment by Beast-Viper** [comment]
Any solution for this?

**Comment by FlynnD273** [comment]
> Any solution for this?

Not on this end, it appears to be a Mutter bug.

**Comment by mockballd** [comment]
Hopefully this will be addressed soon by the Mutter team. In the meanwhile: would it be feasible to assign the pinch gesture behaviour to another gesture? I would very much like to have a three finger swipe down gesture invoke the Ctrl+W shortcut.

I haven't taken a very close look at the code yet. Could someone point me in the right direction?

**Comment by FlynnD273** [comment]
> Hopefully this will be addressed soon by the Mutter team. In the meanwhile: would it be feasible to assign the pinch gesture behaviour to another gesture? I would very much like to have a three finger swipe down gesture invoke the Ctrl+W shortcut.
> 
> I haven't taken a very close look at the code yet. Could someone point me in the right direction?

I'm sure it's possible! I think you should just be able to change [this case](https://github.com/sidevesh/gnome-gesture-improvements--transpiled/blob/3bc46f0c3804c3a399b3023598445b819e665af0/gestureImprovements%40gestures/src/snapWindow.js#L99) with `this._keyboard.sendKeys([Clutter.KEY_Control_L, Clutter.KEY_w]);` from [this line](https://github.com/sidevesh/gnome-gesture-improvements--transpiled/blob/3bc46f0c3804c3a399b3023598445b819e665af0/gestureImprovements%40gestures/src/pinchGestures/closeWindow.js#L95) in the CloseWindow file. This is what sends the Ctrl+W shortcut. 

For installing the extension, you should just be able to zip the `gestureImprovements@gestures` directory and run `gnome-extensions install gestureImprovements@gestures.zip`. You _might_ have to run `glib-compile-schemas schemas/` before that to compile the schemas too though. I remember having issues with that when I was poking around trying to figure out why pinch gestures weren't working.

**Comment by mockballd** [comment]
Great! For anyone interested, replace lines 100, 101 and 102 [here](https://github.com/sidevesh/gnome-gesture-improvements--transpiled/blob/3bc46f0c3804c3a399b3023598445b819e665af0/gestureImprovements%40gestures/src/snapWindow.js#L100-L102) with
```this._virtualDevice.sendKeys([Clutter.KEY_Control_L, Clutter.KEY_w]);```

Much appreciated, @FlynnD273!

**Comment by Beast-Viper** [comment]
> Great! For anyone interested, replace lines 100, 101 and 102 [here](https://github.com/sidevesh/gnome-gesture-improvements--transpiled/blob/3bc46f0c3804c3a399b3023598445b819e665af0/gestureImprovements%40gestures/src/snapWindow.js#L100-L102) with `this._virtualDevice.sendKeys([Clutter.KEY_Control_L, Clutter.KEY_w]);`
> 
> Much appreciated, @FlynnD273!

Hello, I tried your suggestion but it didn't work. Maybe I should set it to some other custom shortcut (Mine uses Meta + Q to exit app).

**Comment by sidevesh** [comment]
Closing this as it is caused by mutter itself in latest GNOME release and I am getting no response on the issues I opened in GNOME GitLab
