### ISSUE TITLE
Bug/Feature request: Update underlying keybinding

### ISSUE THREAD

**Issue by thyttan** [sidevesh/gnome-gesture-improvements--transpiled#8]
Duplicate of: https://github.com/harshadgavali/gnome-gesture-improvements/issues/142#issue-1448405061

> If the user changes the keybinding of one of the functions Gesture Improvements can do - it can't do it anymore!
>
> I'd like for Gesture Improvements to look if the user have changed the keybindings in system settings and update accordingly.
>
> Alternatively let the user define what keybinding should be tied to the different gestures.

Personally I've changed to match my keyboard shortcuts, but I have not introduced a way to change underlying mappings from the extension settings. See diff here: https://github.com/sidevesh/gnome-gesture-improvements--transpiled/commit/0f82afd5062fbbef4682900e2982984747dfd0a7

**Comment by sidevesh** [comment]
This transpiled repo is not in a state where it new features could be added,
my goal is at max to keep it working with newer Gnome version.
